### ISSUE TITLE
Better README / Chrome ext. page

### ISSUE THREAD

**Issue by mguida22** [mguida22/buzzkill#26]
We need a more descriptive readme and chrome ext. page. This should include:
- Better description
- Instructions to run locally
- Screenshot(s)
- Philosophy/goals/plans
- How to help

**Comment by mguida22** [comment]
@agent-reed 1280x800 size screen shots

**Comment by agent-reed** [comment]
<img width="640" alt="screen1" src="https://cloud.githubusercontent.com/assets/10404138/10717602/07f2e4f0-7b23-11e5-9ab0-9454741c6afb.png">

**Comment by agent-reed** [comment]
<img width="640" alt="screen2" src="https://cloud.githubusercontent.com/assets/10404138/10717628/a70f5154-7b23-11e5-8dc3-f1bed6ce297d.png">

**Comment by mguida22** [comment]
<img width="579" alt="screen shot 2015-10-25 at 3 40 52 pm" src="https://cloud.githubusercontent.com/assets/9451227/10718037/d22e9830-7b2e-11e5-8974-0b7be5fc95a0.png">
