### ISSUE TITLE
Inserts slider onto page

### ISSUE THREAD

**Issue by mguida22** [mguida22/buzzkill#33]
The slider gets put onto the page here http://www.colorado.edu/

<img width="1128" alt="screen shot 2015-11-03 at 2 04 27 pm" src="https://cloud.githubusercontent.com/assets/9451227/10923997/2f6b70a4-8241-11e5-91c2-af98b8f5c5dc.png">

cc @agent-reed

**Comment by agent-reed** [comment]
ha. what

**Comment by mguida22** [comment]
It was an issue with the id we were using to reference the slider. The id was simply `slider` and so on a page that uses the same id it hijacked it. I switched all the ids to be prefixed with buzzkill so now they look like `buzzkill-slider`
